script for fixing ntfs errors

diff --git a/chkdsk b/chkdsk
--- a/chkdsk
+++ b/chkdsk
@@ -19,7 +19,7 @@ fi;
 #Найти все разделы ntfs
 win=$(blkid | grep 'TYPE="ntfs"' | cut -f1 -d':')
 #Разделы не найдены = выйти
-if [ -z $win ]; then echo "ntfs volumes not found, exit..."; exit 1; fi
+if [[ -z $win ]]; then echo "ntfs volumes not found, exit..."; exit 1; fi
 
 #Демонтаж, проверка, монтирование каждого раздела; (-b tries to fix bad clusters and -d to fix dirty states)
 for vol in $win; do umount -l $vol; ntfsfix -d $vol; mount $vol; done
